spring:
  cloud:
    gateway:
      routes:
      - id: webhook
        #uri: http://${uri_webhook:webhook.169.56.84.41.nip.io}
        uri: ${uri_webhook:http://webhook.169.56.84.41.nip.io}
        predicates: 
        - Path=/greeting/**
    loadbalancer:
      ribbon:
        enabled: false        