spring:
  cloud:
    gateway:
      routes:
      - id: webhook
        uri: ${uri_webhook:http://localhost:8000}
        predicates: 
        - Path=/greeting/**
    loadbalancer:
      ribbon:
        enabled: false        