spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false        
---
# Before, After, Between
spring.cloud.gateway:
  routes: 
  - id: hystrix-producer-v1
    uri: lb://hystrix-producer
    predicates: 
    - Path=/api/coffees/**
    #- Before=2020-12-31T23:59:59+09:00[Asia/Seoul]
  - id: hystrix-producer-v2
    # ex) /hystrix-producer/
    uri: lb://hystrix-producer
    predicates:
    - Path=/hystrix-producer/v2/**
    #- After=2021-01-01T00:00:00+09:00[Asia/Seoul]
    filters:
    - RewritePath=/hystrix-producer/v2/(?<segment>.*), /$\{segment}
    - PrefixPath=/api

---

