
spring:
  cloud:
    gateway:
      routes:
      - id: webhook
        #uri: http://${uri_webhook:webhook.169.56.84.41.nip.io}
        uri: lb://webhook
        predicates: 
        - Path=/greeting/**
