spring:
  cloud:
    gateway:
      routes:
      - id: webhook
        uri: http://${uri_webhook:webhook.169.56.84.41.nip.io}
        predicates: 
        - Path=/greeting/**


management:
  endpoints:
    web:
      exposure:
        include: '*'
        
  endpoint:
    gateway:
      enabled: true
