spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false        
---
spring.cloud.gateway:
  routes: 

# ======== Predigates factories ============
  - id: hystrix-producer-event 
    uri: lb://hystrix-producer
    predicates:
    - Path=/hystrix-producer/**
    - Between=3021-02-04T00:00:00+09:00[Asia/Seoul],3021-02-04T23:59:59+09:00[Asia/Seoul]
    filters:
    - RewritePath=/hystrix-producer/(?<segment>.*), /coffees/delay  # Rewrite rule
    - PrefixPath=/api  #무조건 앞에 붙이는 문자열 

  - id: hystrix-producer-old
    uri: lb://hystrix-producer
    predicates: 
    - Path=/api/coffees/**
    - Before=2020-12-31T23:59:59+09:00[Asia/Seoul]

  - id: hystrix-producer-new
    # ex) /hystrix-producer/coffees/pass => <uri>/api/coffees/pass
    uri: lb://hystrix-producer
    predicates:
    - Path=/hystrix-producer/**
    - After=2021-01-01T00:00:00+09:00[Asia/Seoul]
    filters:
    - RewritePath=/hystrix-producer/(?<apiuri>.*), /${apiuri}  # 그룹갭처 '(?<group>pattern)', group명에 특수문자 쓰지 않기 
    - PrefixPath=/api  #무조건 앞에 붙이는 문자열 
    
# Predicates: Cookie
  - id: hystrix-producer-cookie
    uri: lb://hystrix-producer
    predicates:
    - Path=/cookie/**
    - Cookie=LTPAToken,* 
    filters: 
    - RewritePath=/(.*), /api/coffees/pass
# Predicates: Header
  - id: hystrix-producer-header 
    uri: lb://hystrix-producer
    predicates:
    - Path=/header/**
    - Header=User-Agent, .+Chrome.*   #only chrome support
    - Header=Host, ^gateway.*         #only from host which start 'gateway' 
    filters: 
    - RewritePath=/(.*), /api/coffees/pass
# Predicates: Host
  - id: hystrix-producer-host 
    uri: lb://hystrix-producer
    predicates:
    - Path=/host/**
    - Host=gateway.**, **.myorg.com   #not regrexp, but Ant-style pattern(?, *. **).
    filters: 
    - RewritePath=/(.*), /api/coffees/pass
# Predicates: Method
  - id: hystrix-producer-method 
    uri: lb://hystrix-producer
    predicates:
    - Path=/method/**
    - Method=Get,POST   # only allow Get, POST.
    filters: 
    - RewritePath=/(.*), /api/coffees/pass
# Predicates: Query
  - id: hystrix-producer-query 
    uri: lb://hystrix-producer
    predicates:
    - Path=/query/**
    - Query=param, ^pass$   # param값이 정확히 pass일때만 routing 
    filters: 
    - RewritePath=/(.*), /api/coffees/pass
# Predicates: Weight -> use it for canari deploy
  - id: hystrix-producer-v1 
    uri: lb://hystrix-producer
    predicates:
    - Path=/weight/**
    - Weight=group1, 6 
    filters: 
    - RewritePath=/(.*), /api/coffees/no-pass
  - id: hystrix-producer-v2
    uri: lb://hystrix-producer
    predicates:
    - Path=/weight/**
    - Weight=group1, 4
    filters: 
    - RewritePath=/(.*), /api/coffees/pass

#========== GatewayFilter factories ============== 

# Request Header: Create
  - id: consumer-reqheader-create 
    uri: lb://consumer
    predicates:
    - Path=/addreqheader/**
    filters:
    - RewritePath=/addreqheader/(?<msg>.*), /greeting/${msg}
    - AddRequestHeader=x-req-msg, Happy

  - id: consumer-reqheader-create2
    uri: lb://consumer
    predicates:
    - Path=/addreqheader2/{greeting}
    filters:
    - AddRequestHeader=x-req-msg, {greeting}
    - RewritePath=/.*/(?<msg>.*), /greeting/${msg} 
  
# Request Header: Update
  # /setreqheader/max-age=86400
  - id: consumer-reqheader-update
    uri: lb://consumer
    predicates:
    - Path=/setreqheader/{cache-control} 
    filters: 
    - RewritePath=/.*/(?<msg>.*), /greeting/${msg} 
    - SetRequestHeader=cache-control, {cache-control}

# Request Header: Delete
  # /rmreqheader/x-removed-header
  - id: consumer-reqheader-delete 
    uri: lb://consumer 
    predicates:
    - Path=/rmreqheader/{rmheader}
    filters:
    - RewritePath=/.*/(?<header>.*), /greeting/${header}
    - AddRequestHeader=x-removed-header, {rmheader}
    - RemoveRequestHeader=x-removed-header
    
# Response Header: Create
  - id: consumer-resheader-create 
    uri: lb://consumer
    predicates:
    - Path=/addresheader/{header}
    filters: 
    - RewritePath=/.*/(?<header>.*), /greeting/${header}
    - AddResponseHeader=x-resheader-create, {header}

# Response Header: Update
  # /setcontenttype/text
  - id: consumer-resheader-update
    uri: lb://consumer 
    predicates:
    - Path=/setcontenttype/{content-type}
    filters: 
    - RewritePath=/.*/(?<type>.*), /greeting/${type}
    - SetResponseHeader=Content-Type, {content-type}

# Response Header: Delete
  - id: consumer-resheader-delete
    uri: lb://consumer 
    predicates:
    - Path=/rmresheader/{rmheader}
    filters: 
    - RewritePath=/.*/(?<header>.*), /greeting/${header}
    - AddResponseHeader=x-header, {rmheader}
    - AddResponseHeader=x-removed-header, x-header
    - RemoveResponseHeader=x-header
 
# Request Parameter: Create 
  # /consumer/hello?svc=consumer&api=greeting
  - id: consumer-routes-by-query
    uri: lb://consumer
    predicates: 
    - Path=/consumer/** 
    - Query=svc, ^consumer$
    - Query=api, ^greeting$
    filters: 
    - RewritePath=/.*/(?<msg>.*), /greeting/${msg}
  
  - id: gateway-reqparam-create
    uri: http://gateway.169.56.84.41.nip.io
    predicates:
    - Path=/addreqparam/**
    filters:
    - RewritePath=/.*/(?<param>.*), /consumer/${param}
    - AddRequestParameter=svc, consumer 
    - AddRequestParameter=api, greeting 

# Request Parameter: Update - same as AddRequestParameter
  - id: consumer-reqparam-update 
    uri: http://gateway.169.56.84.41.nip.io
    predicates: 
    - Path=/setreqparam/**
    - Query=svc, ^webhook$ 
    - Query=api, ^greeting$   
    filters:
    - RewritePath=/.*/(?<msg>.*), /consumer/${msg} 
    - AddRequestParameter=svc, consumer
    - AddRequestParameter=api, greeting 

# Request Parameter: Delete 
  - id: consumer-reqparam-delete 
    uri: http://gateway.169.56.84.41.nip.io
    predicates: 
    - Path=/rmreqparam/** 
    - Query=svc, consumer 
    - Query=api, greeting 
    filters: 
    - RewritePath=/.*/(?<msg>.*), /consumer/${msg} 
    
