spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false        
---
# Predicates: Before, After, Between
spring.cloud.gateway:
  routes: 
  - id: hystrix-producer-new
    # ex) /hystrix-producer/coffees/pass => <uri>/api/coffees/pass
    uri: lb://hystrix-producer
    predicates:
    - Path=/hystrix-producer/**
    #- After=2021-01-01T00:00:00+09:00[Asia/Seoul]
    filters:
    - RewritePath=/hystrix-producer/(?<segment>.*), /$\{segment}  # Rewrite rule
    - PrefixPath=/api  #무조건 앞에 붙이는 문자열 

