spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false        
---
# Before, After, Between
spring.cloud.gateway:
  routes: 
  - id: hystrix-producer-event 
    uri: lb://hystrix-producer
    predicates:
    - Path=/hystrix-producer/**
    - Between=3021-02-04T00:00:00+09:00[Asia/Seoul],3021-02-04T23:59:59+09:00[Asia/Seoul]
    filters:
    - RewritePath=/hystrix-producer/(?<segment>.*), /coffees/delay  # Rewrite rule
    - PrefixPath=/api  #무조건 앞에 붙이는 문자열 

  - id: hystrix-producer-old
    uri: lb://hystrix-producer
    predicates: 
    - Path=/api/coffees/**
    - Before=2020-12-31T23:59:59+09:00[Asia/Seoul]

  - id: hystrix-producer-new
    # ex) /hystrix-producer/coffees/pass => <uri>/api/coffees/pass
    uri: lb://hystrix-producer
    predicates:
    - Path=/hystrix-producer/**
    - After=2021-01-01T00:00:00+09:00[Asia/Seoul]
    filters:
    - RewritePath=/hystrix-producer/(?<segment>.*), /$\{segment}  # Rewrite rule
    - PrefixPath=/api  #무조건 앞에 붙이는 문자열 
    
---
# Cookie
spring.cloud.gateway:
  routes: 
  - id: hystrix-producer-event 
    uri: lb://hystrix-producer
    predicates:
    - Path=/cookie/**
    - Cookie=LTPAToken,* 
    filters: 
    - RewritePath=/(.*), /api/coffees/pass
--- 
# Request Header
spring.cloud.gateway:
  routes: 
  - id: hystrix-producer-event 
    uri: lb://hystrix-producer
    predicates:
    - Path=/header/**
    #- Header=User-Agent,(?Chrome.*)
    filters: 
    - RewritePath=/(.*), /api/coffees/pass
