spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false        
---
spring.cloud.gateway:
  routes: 
  - id: webhook-v1
    uri: ${uri_webhook:http://localhost:8000}
    predicates: 
    - Path=/greeting/**
    - Before=2020-12-31T23:59:59+09:00[Asia/Seoul]
  - id: webhook-v2
    uri: ${uri_webhook:http://localhost:8000}
    predicates:
    - Path=/webhook/**
    - After=2021-01-01T00:00:00+09:00[Asia/Seoul]
    filters:
    - RewritePath=/webhook/(?<segment>.*), /$\{segment}
    
