ribbon:
  ConnectTimeout: 2000             
  ReadTimeout: 2000                 
  NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
  ServerListRefreshInterval: 60000
  NIWSServerListFilterClassName: com.netflix.loadbalancer.ServerListSubsetFilter

sleeptime: 5000
---
spring:
  sleuth: 
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411
   
management.endpoints.web.exposure.include: prometheus
